name: Install Package and Create PR

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name to be installed"
        required: true

jobs:
  install_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Add package
        run: yarn add ${{ github.event.inputs.package_name }}

      - name: Setup Git authentication
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create branch and commit changes
        run: |
          PACKAGE_NAME=$(echo "${{ github.event.inputs.package_name }}" | sed 's/\//-/g')
          BRANCH_NAME="add-$PACKAGE_NAME-$(date +%s)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "chore: install ${{ github.event.inputs.package_name }}"

      - name: Push branch
        run: |
          PACKAGE_NAME=$(echo "${{ github.event.inputs.package_name }}" | sed 's/\//-/g')
          BRANCH_NAME="add-$PACKAGE_NAME-$(date +%s)"
          git push origin $BRANCH_NAME

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "chore: install ${{ github.event.inputs.package_name }}"
          body: "This PR installs ${{ github.event.inputs.package_name }} to the project."
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
